trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-CIJ61FT

steps:
- script: echo "CI pipeline triggered by GitHub push"
  displayName: "Run echo"
